pipeline {
  agent {
    kubernetes {
      label 'ansible-agent'  // all your pods will be named with this prefix, followed by a unique id
      idleMinutes 2  // how long the pod will live after no jobs have run on it
      yamlFile 'jenkins/pods.yaml'  // path to the pod definition relative to the root of our project 
      defaultContainer 'ansible'  // define a default container if more than a few stages use it, will default to jnlp container
    }
  }
  stages{
    // stage('SCM Checkout'){
    //     steps{
    //         git branch: 'main', url: 'https://github.com/shoot4daclouds/ansible-tf-nagios-server.git'
    //     }

    stage('Build') {
      steps {  // no container directive is needed as the maven container is the default
        sh "ansible --version"   
      }
    }
  }
}