--- 

nagios_dependencies:
  - httpd 
  - php
  - gcc
  - glibc
  - glibc-common
  - wget
  - perl
  - gd
  - gd-devel
  - unzip
  - zip

user: nagios
group: nagcmd

nagios_server_ports:
  - 80/tcp
  - 443/tcp
  